blank_issues_enabled: true
contact_links:
  - name: Haven Official Website
    url: https://mangdang.org
    about: 激活设备、配置 AI、声纹识别、声音克隆等应有尽有，DIY 属于你自己的 Haven
  - name: Haven AI 聊天机器人百科全书
    url: https://ccnphfhqs21z.feishu.cn/wiki/F5krwD16viZoF0kKkvDcrZNYnhb
    about: 开发文档、硬件制作、烧录教程、FAQ尽在 Haven 百科